sadf
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -197,11 +197,11 @@ deploy_multus:
 	- rm -rf $(E2E_MULTUS_CNI_CONFIG_DIR)/*
 	set -x ; echo "install cni and route on nodes" ; \
 		TMP=$$( docker exec $(E2E_KIND_MASTER_NODE_NAME) ip a s eth0 ) || { echo "error, failed to find master ip" ; exit 1 ; } ; \
-		MASTER_IPV4_ADDR=$${ grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' <<< "$${TMP}" } || true ; \
-		MASTER_IPV6_ADDR=$${ echo "$${TMP}" |  grep -v "scope link" | grep -oP '(?<=inet6\s)[0-9a-f:]+' } || true ; \
-		TMP=$${ docker exec $(E2E_KIND_WORKER_NODE_NAME) ip a s eth0 } || { echo "error, failed to find worker ip" ; exit 1 ; } ; \
-		WORKER_IPV4_ADDR=$${ grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' <<< "$${TMP}" } || true ; \
-		WORKER_IPV6_ADDR=$${ echo "$${TMP}" |  grep -v "scope link" | grep -oP '(?<=inet6\s)[0-9a-f:]+' } || true ; \
+		MASTER_IPV4_ADDR=$$( grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' <<< "$${TMP}" ) || true ; \
+		MASTER_IPV6_ADDR=$$( echo "$${TMP}" |  grep -v "scope link" | grep -oP '(?<=inet6\s)[0-9a-f:]+' ) || true ; \
+		TMP=$$( docker exec $(E2E_KIND_WORKER_NODE_NAME) ip a s eth0 ) || { echo "error, failed to find worker ip" ; exit 1 ; } ; \
+		WORKER_IPV4_ADDR=$$( grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' <<< "$${TMP}" ) || true ; \
+		WORKER_IPV6_ADDR=$$( echo "$${TMP}" |  grep -v "scope link" | grep -oP '(?<=inet6\s)[0-9a-f:]+' ) || true ; \
 		echo "master ipv4=$${MASTER_IPV4_ADDR}, ipv6=$${MASTER_IPV6_ADDR} " ; \
 		echo "worker ipv4=$${WORKER_IPV4_ADDR}, ipv6=$${WORKER_IPV6_ADDR} "
 	echo "install cni and route on nodes" ; \
