pick
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/cherrypick.yaml b/.github/workflows/cherrypick.yaml
--- a/.github/workflows/cherrypick.yaml
+++ b/.github/workflows/cherrypick.yaml
@@ -64,8 +64,9 @@ jobs:
           #export GIT_AUTHOR_NAME="weizhou.lan"
           #export GIT_AUTHOR_EMAIL="email@example.com"
           #=------------------ get the commits
-          
-          
+          ALL_COMMITS=` git log  --left-right  ${{ github.head_ref }} ...${{ github.base_ref }} | grep "commit <" | awk '{print $3}' | tr '\n' ' ' `
+          [ -z "$ALL_COMMITS" ] && echo "error, failed to get any commits" && exit 1
+          echo "============ commits: ${ALL_COMMITS} "
           #--- cherry pick
           for BRANCH in $WANT_MERGE_BRANCH_LIST ; do
               echo "---- cherry for ${BRANCH}"
@@ -78,7 +79,22 @@ jobs:
                   echo "error, failed to checkout to branch $BRANCH"
                   continue
               fi
-              git branch
+              git branch --show-current
+              FALIED=false
+              for COMMIT in $ALL_COMMITS ; do
+                  if ! git cherry-pick $COMMIT ; then 
+                    FALIED=true 
+                    echo "error, failed to cherry pick $COMMIT" 
+                    break 
+                  fi
+              done
+              if [ "$FALIED" == "true" ] ; then
+                echo "failed to cherry pick to branch $BRANCH "
+                # create a issue
+              else
+                echo "succeeded to cherry pick to branch $BRANCH "
+                # create a pr   
+              fi 
           done
           echo "all done"
           exit 0
