dasf
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/cherry-pick.yaml b/.github/workflows/cherry-pick.yaml
--- a/.github/workflows/cherry-pick.yaml
+++ b/.github/workflows/cherry-pick.yaml
@@ -46,20 +46,16 @@ jobs:
 
       - name: cherry pick
         run: |
-          if [ ! -f "./tools/cherry/cherry.sh" ] ; then 
-              echo "warning ,there is no /tools/cherry/cherry.sh in branch ${{ matrix.releaseName }}, ignore cherry pick "
-              exit 0
-          fi
           echo "labels: ${{ steps.pr-labels.outputs.labels }}"
           echo "author: ${{ github.event.pull_request.user.login }}"
-          echo "GITHUB_REF: ${GITHUB_REF##*/}"
+          #echo "GITHUB_REF: ${GITHUB_REF##*/}"
           echo "url: ${{ steps.pr-url.outputs.url }}"
-          echo "sha: ${{ github.sha }}"
-          echo "github.base_ref: ${{ github.base_ref }}"
+          #echo "sha: ${{ github.sha }}"
+          #echo "github.base_ref: ${{ github.base_ref }}"
           echo "github.head_ref: ${{ github.head_ref }}"
-          echo "github.ref: ${{ github.ref }}"
-          echo "github.ref_name: ${{ github.ref_name }}"
-          echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
+          #echo "github.ref: ${{ github.ref }}"
+          #echo "github.ref_name: ${{ github.ref_name }}"
+          #echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
           echo "github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"
           #--
           BINGO=false
@@ -70,6 +66,10 @@ jobs:
           [ "$BINGO" == "false" ] && echo "no need to cherry pick to ${{ matrix.releaseName }}" && exit 0
           #--
           echo "============= it is required to cherry pick to ${{ matrix.releaseName }} ============"
+          if [ ! -f "./tools/cherry/cherry.sh" ] ; then 
+              echo "error ,there is no /tools/cherry/cherry.sh in branch ${{ matrix.releaseName }} "
+              exit 1
+          fi
           chmod +x ./tools/cherry/cherry.sh
           export CHERRY_FROM_BRANCH=${{ github.head_ref }}
           git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
