d
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

da

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/cherrypick.yaml b/.github/workflows/cherrypick.yaml
--- a/.github/workflows/cherrypick.yaml
+++ b/.github/workflows/cherrypick.yaml
@@ -1,14 +1,15 @@
-name: CherryPick PR
+name: Auto CherryPick PR
 
 permissions: write-all
 
 env:
   LABEL_PREFIX_CHERRYPICK: "cherrypick-"
+  CHERRYPICK_LABEL: "robot-cherrypick"
+  DEFAULT_REVIEWER: "weizhoublue"
 
 on:
   pull_request_target:
     types:
-      - opened
       - closed
 
 jobs:
@@ -20,108 +21,120 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - uses: kceb/pull-request-url-action@v1
-#        id: pr-url
-
       - name: cherry pick
         run: |
           set -x
-          #====
+          echo "============ print var ======== "
           PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"
-          echo "labels: ${PR_LABLES}"
+          ACTION_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           echo "number: ${{ github.event.number }}"
+          echo "action url: ${ACTION_URL}"
           echo "author: ${{ github.event.pull_request.user.login }}"
-          #echo "GITHUB_REF: ${GITHUB_REF##*/}"
           echo "url: ${PR_URL}"
-          #echo "url: ${{ steps.pr-url.outputs.url }}"
-          #echo "sha: ${{ github.sha }}"
           echo "pr to branch, github.base_ref: ${{ github.base_ref }}"
           echo "pr branch name, github.head_ref: ${{ github.head_ref }}"
-          #echo "github.ref: ${{ github.ref }}"
-          #echo "github.ref_name: ${{ github.ref_name }}"
-          #echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
           echo "pr latest commit, github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"
-          #== get labels
+          #
+          #
+          echo "============ get labels ======== "
           echo ${{ secrets.WELAN_PAT }} | gh auth login --with-token
           gh pr view ${{ github.event.number }} | grep -i "^labels:"
-          PR_LABLES=` gh pr view ${{ github.event.number }} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
-          #=== loop labels and get merge branchs
+          PR_LABEL=` gh pr view ${{ github.event.number }} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
+          echo "PR_LABEL: ${PR_LABEL}"
+          #
+          #
+          echo "============ get dest branch from labels ======== "
           WANT_MERGE_BRANCH_LIST=""
-          for LABEL in ${PR_LABLES} ; do
-              echo "checking lable $LABEL "
+          for LABEL in ${PR_LABEL} ; do
+              echo "checking label $LABEL "
               PREFIX="${{ env.LABEL_PREFIX_CHERRYPICK }}"
               grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
               BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
               WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
           done
-          [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no need to cherry pick" && exit 0
-          echo "============= it is required to cherry pick to $WANT_MERGE_BRANCH_LIST ============"
-          chmod +x ./tools/cherry/cherry.sh
+          [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no branch to cherry pick" && exit 0
+          echo "cherry pick to $WANT_MERGE_BRANCH_LIST "
+          #
+          #
+          echo "============= get new commits from ${{ github.head_ref }} to ${{ github.base_ref }} ============"
           git branch
           git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} || true
           git fetch origin ${{ github.head_ref }}:${{ github.head_ref }} || true
-          git config --global user.email "you@example.com"
-          git config --global user.name "weizhou.lan"
-          #export GIT_AUTHOR_NAME="weizhou.lan"
-          #export GIT_AUTHOR_EMAIL="email@example.com"
-          #=------------------ get the commits
+          git config --global user.email "robot@example.com"
+          git config --global user.name "robot"
           git checkout ${{ github.head_ref }}
           git log  --left-right  ${{ github.head_ref }} ...${{ github.base_ref }} 
           ALL_COMMITS=` git log  --left-right  ${{ github.head_ref }} ...${{ github.base_ref }} | grep "commit <" | awk '{print $3}' | tr '\n' ' ' `
           [ -z "$ALL_COMMITS" ] && echo "error, failed to get any commits" && exit 1
-          echo "============ commits: ${ALL_COMMITS} "
-          #--- cherry pick
+          echo "commits for cherry pick: ${ALL_COMMITS} "
+          #
+          #
+          echo "============ begin to cherry pick ============ "
+          FAILURE_COUNTER=0
           for BRANCH in $WANT_MERGE_BRANCH_LIST ; do
-              echo "---- cherry for ${BRANCH}"
+              GH_FAILED_OPTION=" --title \"failed to auto cherry pick PR ${{ github.event.number }} to branch ${BRANCH} \"  "
+              GH_FAILED_OPTION+=" --label \"${{ env.CHERRYPICK_LABEL }},pr-${{ github.event.number }}\" "
+              GH_FAILED_OPTION+=" --assignee ${{ github.event.pull_request.user.login }},${{ env.DEFAULT_REVIEWER }} "
+              echo "************** cherry for branch ${BRANCH}"
               if ! git ls-remote --exit-code --heads origin ${BRANCH} ; then
                   # todo: create issue
                   echo "error, branch $BRANCH does not exist"
+                  gh issue create ${GH_FAILED_OPTION} \
+                      --body "reason: the branch $BRANCH does not exist. [ pr ${PR_URL} ] [ action ${ACTION_URL} ] "
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create issue"
+                      ((FAILURE_COUNTER++))
+                  fi
                   continue
               fi
               git fetch origin ${BRANCH}:${BRANCH} || true
               if ! git checkout ${BRANCH} ; then
                   echo "error, failed to checkout to branch $BRANCH"
+                  gh issue create ${GH_FAILED_OPTION} \
+                      --body "reason: failed to get the branch $BRANCH. [ pr ${PR_URL} ] [ action ${ACTION_URL} ] "
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create issue"
+                      ((FAILURE_COUNTER++))
+                  fi
                   continue
               fi
               git branch --show-current
-              FALIED=false
+              FAIL=false
               for COMMIT in $ALL_COMMITS ; do
                   if ! git cherry-pick $COMMIT ; then 
-                    FALIED=true 
+                    FAIL=true 
                     echo "error, failed to cherry pick $COMMIT" 
                     git cherry-pick --abort
                     git reset --hard HEAD 
-                    break 
+                    break
                   fi
               done
-              if [ "$FALIED" == "true" ] ; then
-                echo "failed to cherry pick to branch $BRANCH "
-                # create a issue
+              if [ "$FAIL" == "true" ] ; then
+                  echo "failed to cherry pick to branch $BRANCH "
+                  gh issue create ${GH_FAILED_OPTION} \
+                        --body "reason: commits conflict when merging to branch $BRANCH, please manually cherry pick it by yourself. [ pr ${PR_URL} ] [ action ${ACTION_URL} ] "
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create issue"
+                      ((FAILURE_COUNTER++))
+                  fi
               else
-                echo "succeeded to cherry pick to branch $BRANCH "
-                # create a pr   
+                  echo "succeeded to cherry pick to branch $BRANCH "
+                  # create a pr
+                  gh pr create --title "auto cherry pick PR ${{ github.event.number }} to branch ${BRANCH}" \
+                      --reviewer "${{ github.event.pull_request.user.login }},${{ env.DEFAULT_REVIEWER }}" \
+                      --label ${{ env.CHERRYPICK_LABEL }},pr-${{ github.event.number }}
+                      --base ${BRANCH}
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create pr"
+                      ((FAILURE_COUNTER++))
+                  fi
               fi 
           done
-          echo "all done"
-          exit 0
-          #
-          if [ ! -f "./tools/cherry/cherry.sh" ] ; then 
-              echo "error ,there is no /tools/cherry/cherry.sh in branch ${{ matrix.releaseName }} "
+          echo "=========== check result ============"
+          if ((FAILURE_COUNTER>0)) ; then
+              echo "error, $FAILURE_COUNTER failuire happened"
               exit 1
-          fi
-          export CHERRY_FROM_BRANCH=${{ github.head_ref }}
-          if ./tools/cherry/cherry.sh "${{ github.event.pull_request.head.sha }}" ; then
-              echo "succeed to cherry pick"
           else
-              echo "error, failed to cherry pick"
-              exit 1
+              echo "all done"
+              exit 0
           fi
-          #--- create pr
-          #echo ${{ secrets.WELAN_PAT }} | gh auth login --with-token
-          #gh pr  create --title 'test' --body 'sadf'  --base ${{ matrix.releaseName }}
-
-
-
-
-
-
