adsf
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/cherry-pick.yaml b/.github/workflows/cherry-pick.yaml
--- a/.github/workflows/cherry-pick.yaml
+++ b/.github/workflows/cherry-pick.yaml
@@ -38,14 +38,16 @@ jobs:
               grep '"username":'  < ${DATA_FILE}
           PR_AUTHOR=` cat ${DATA_FILE} | grep '"username":'  | awk -F'"' '{print $4}' | sort | uniq  | grep -v "web-flow"  | head -1 | tr -d '\n' `
               [ -n "${PR_AUTHOR}" ] || { echo "no PR_AUTHOR, ignore" ; }
-          CHERRY_PICK_COMMIT=${{ github.sha }}
           gh pr view ${PR_NUMBER}
           PR_LABEL=` gh pr view ${PR_NUMBER} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
               [ -n "${PR_AUTHOR}" ] || { echo "no PR_LABEL, ignore" ; }
           #
+              cat ${DATA_FILE} | grep -Ei "https://github.com/.*/commit"
+          PR_COMMITS= ` cat ${DATA_FILE} | grep -Ei "https://github.com/.*/commit" | awk -F'"' '{print $4}' | uniq -c | awk '{ if ($1 == 1 ) print $2}' | awk -F'/' '{print $NF}' | tr '\n' ' '  `
+              [ -n "${PR_COMMITS}" ] || { echo "no PR_COMMITS, ignore" ; }
           echo "number: ${PR_NUMBER}"
           echo "action url: ${ACTION_URL}"
-          echo "CHERRY_PICK_COMMIT: ${CHERRY_PICK_COMMIT}"
+          echo "PR_COMMITS: ${PR_COMMITS}"
           echo "author: ${PR_AUTHOR}"
           echo "url: ${PR_URL}"
           echo "PR_LABEL: ${PR_LABEL}"
@@ -95,10 +97,18 @@ jobs:
                   continue
               fi
               git branch --show-current
-              if ! git cherry-pick $CHERRY_PICK_COMMIT ; then 
-                  echo "error, failed to cherry pick $CHERRY_PICK_COMMIT to branch $BRANCH "
-                  git cherry-pick --abort || true
-                  git reset --hard HEAD  || true
+              FAIL=false
+              for COMMIT in $PR_COMMITS  ; do
+                  if ! git cherry-pick $COMMIT ; then 
+                    FAIL=true 
+                    echo "error, failed to cherry pick $COMMIT" 
+                    git cherry-pick --abort || true
+                    git reset --hard HEAD || true
+                    break
+                  fi
+              done
+              if [ "$FAIL" == "true" ] ; then
+                  echo "failed to cherry pick to branch $BRANCH "
                   gh issue create ${GH_FAILED_OPTION} \
                         --body "reason: commits conflict when merging to branch $BRANCH, please manually cherry pick it by yourself. [ pr ${PR_URL} ] [ action ${ACTION_URL} ] "
                   if (($?!=0)) ; then
@@ -106,11 +116,11 @@ jobs:
                       ((FAILURE_COUNTER++))
                   fi
               else
-                  echo "succeeded to cherry pick $CHERRY_PICK_COMMIT to branch $BRANCH "
+                  echo "succeeded to cherry pick to branch $BRANCH "
                   # create a pr
-                  gh pr create --title "auto cherry pick PR ${PR_NUMBER} to branch ${BRANCH}" \
-                      --reviewer "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
-                      --label ${{ env.CHERRYPICK_LABEL }},pr-${PR_NUMBER}
+                  gh pr create --title "auto cherry pick PR ${{ github.event.number }} to branch ${BRANCH}" \
+                      --reviewer "${{ github.event.pull_request.user.login }},${{ env.DEFAULT_REVIEWER }}" \
+                      --label ${{ env.CHERRYPICK_LABEL }},pr-${{ github.event.number }}
                       --base ${BRANCH}
                   if (($?!=0)) ; then
                       echo "!!!! error, failed to create pr"
