wrong
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/lint-yaml.yaml b/.github/workflows/lint-yaml.yaml
--- a/.github/workflows/lint-yaml.yaml
+++ b/.github/workflows/lint-yaml.yaml
@@ -36,6 +36,36 @@ jobs:
         if: ${{ github.event_name != 'workflow_dispatch' }}
         uses: actions/checkout@v3
 
+    - name: yaml format yq
+        env:
+          GITHUB_TOKEN: ${{ secrets.WELAN_PAT}}
+        run: |
+          echo "=================== install yq"
+          wget https://github.com/mikefarah/yq/releases/download/v4.30.7/yq_linux_amd64
+          chmod +x yq_linux_amd64
+          echo "=================== get pr number"
+          DATA_FILE="/tmp/`date +%Y%m%d%H%M%S%N`"
+          echo '${{ toJSON(github) }}' > ${DATA_FILE}
+          cat ${DATA_FILE}
+          grep -Eio "Merge pull request #[0-9]+ " < ${DATA_FILE} || true
+          PR_NUMBER=` cat ${DATA_FILE} | grep -Eio "Merge pull request #[0-9]+ " | grep -Eo "[0-9]+" | uniq ` || true
+              [ -n "${PR_NUMBER}" ] || { echo "no PR number, ignore" ; exit 0 ; }          
+          echo "============= get changed chart========"
+          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"
+          files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
+          echo "files_changed_data: $files_changed_data"
+          files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
+          echo "files_changed: $files_changed"
+          for FILEPATH in $files_changed ; do
+              if grep -E "*\.yaml" $FILEPATH &>/dev/null || grep -E "*\.yml" $FILEPATH &>/dev/null ; then
+                  echo "------------ checking ${FILEPATH} "
+                  if ! yq_linux_amd64 ${FILEPATH} ; then 
+                    echo "error, $FILEPATH is not yaml format"
+                    exit 1
+                  fi
+              fi
+          done
+
       - name: yaml-lint
         id: yaml-lint
         continue-on-error: true
